### PR TITLE
Removed unnecessary files from the gh-pages

### PR DESCRIPTION
**Pull request by juanecabellob**

### CODE REVIEW

**Comment by metalmatze** [comment]
Could you please explain more when creating pull requests.
Why are those files unnecessary?

**Comment by juanecabellob** [comment]
because for the gh-pages you only need the html to produce an output like this one: 
http://juanecabellob.github.io/circuit/

**Comment by juanecabellob** [comment]
so you don't need any other path

**Comment by metalmatze** [comment]
So you moved the doxygen docs and removed the unnecessary other files?

**Comment by juanecabellob** [comment]
I put the doxygen docs in the root and yes, i removed the unnecessary files

**Comment by Gjum** [comment]
@MetalMatze The application code is not needed on the web page.

**Pull request merged**
