### PR TITLE
Feature write post

### LINKED ISSUE #65: As a user, I want to write a post, so that everyone can read it.

### PR DESCRIPTION
**Pull request by KjellPirschel**
closes #65

### CODE REVIEW

**Comment by Gjum** [comment]
:+1:

**Comment by metalmatze** [comment]
Short note: feature branch naming should be: `feature/write-post` but that's no problem.

**Comment by metalmatze** [comment]
While running `python manage.py makemigrations` I get this error

```
You are trying to add a non-nullable field 'created_at' to post without a default; we can't do that (the database needs something to populate existing rows).
Please select a fix:
 1) Provide a one-off default now (will be set on all existing rows)
 2) Quit, and let me add a default in models.py
```

Please fix and push the fix to this branch. Then I will take a look again.

**Comment by Gjum** [comment]
@MetalMatze We just forgot to commit the migration file for this PR.
When we noticed, we [added it to the other PR](https://github.com/KjellPirschel/circuit/commit/b81a4cf74dbae6067996ce2cf0b42f0b62bc7bfd) of that day.
The migration file should have been added in [this commit](https://github.com/KjellPirschel/circuit/commit/dd5614165417bd4a011212aeecd453110bf2e205#diff-7deccb9e6c015b4321878ae268fa3bd8R9) instead.

**Pull request merged**
