### PR TITLE
user login

### PR DESCRIPTION
**Pull request by Gjum**
WIP only for the looks

### CODE REVIEW

**Comment by metalmatze** [comment]
So this does not actually log the user in and out?

**Comment by Iotka** [comment]
No sorry, for more Info see gitter.im. I will fix it this weekend and upload the design-idea.

**Comment by metalmatze** [comment]
The deadline was yesterday.

**Comment by Iotka** [comment]
The basic functionallity is there but there is already a bug.

**Comment by metalmatze** [comment]
This is obsolete now, see #79

**Pull request closed without merging**
