### PR TITLE
Layout fixes

### LINKED ISSUE #198: Improve the design of post edit page
Put the edit form inside panel (card, paper) and make it horizontally bigger.

download 8

### PR DESCRIPTION
**Pull request by juanecabellob**
closes #198

### CODE REVIEW

**Comment by Gjum** [comment]
pics plz

**Comment by metalmatze** [comment]
Pics or not UI changes :relaxed:

**Comment by juanecabellob** [comment]
coming soon..

**Comment by Gjum** [comment]
pics!!!1!

**Comment by juanecabellob** [comment]
Navbar
image

Navbar settings panel
image

New user profile view
image

Edit profile view with panels 
image

Edit post with panels
image

**Comment by Gjum** [comment]
mm not bad. @MetalMatze?

**Comment by Gjum** [comment]
merge develop please.

**Comment by metalmatze** [comment]
:+1:

**Pull request merged**
