### PR TITLE
Feature/django

### PR DESCRIPTION
**Pull request by metalmatze**
@juanecabellob has created this branch with a django project folder inside.

### CODE REVIEW

**Comment by metalmatze** [comment]
2 things:

I would prefer to have the django project inside the root folder, not in a separate sub folder.
I think you shouldn't commiting the `.idea` folder inside the project.

**Comment by Gjum** [comment]
`.gitignore` anyone?

**Comment by metalmatze** [comment]
I think I'm going to create another branch and propose a other structure there. With a `.gitignore` etc.

**Comment by Gjum** [comment]
something along

```
*__pycache__/
*.py[cod]
*.idea*
```

**Comment by metalmatze** [comment]
I gonna include this one https://github.com/github/gitignore/blob/master/Python.gitignore

**Comment by Gjum** [comment]
ok, but then also [the JetBrains one](https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore)

**Comment by metalmatze** [comment]
Good point. I'm going to append that after python's.

**Comment by juanecabellob** [comment]
it makes no sense to handle this as a feature outside the master, because now in order to start with the project, the have to pull it from this branch, and this may lead to confusion.
both .gitignore files should be as well in the master, then every new feature should be forked from master and not from any other branch

**Comment by juanecabellob** [comment]
i know it breaks against our first rules, but there is nothing to worry about when the project is empty. 
and yes, definitely the .idea shouldn't be there, i didn't see that one

**Comment by metalmatze** [comment]
Yeah, but I would like the project to be in the root, not in a sub folder.

**Comment by metalmatze** [comment]
Please take a look at https://github.com/MetalMatze/circuit/tree/feature/django-in-root

There the `manange.py` is in the root folder etc.
I would propose that version, when I'm done.

**Comment by juanecabellob** [comment]
Still, it's an empty project, those changes can be still made on the master branch. Another thing is, that someone should do the first model for users, and put it as well in the master, because if not, the conflicts will present by every pull request, as everybody will have to merge their own user model, and at the end will be everything just more confusing..

**Comment by metalmatze** [comment]
That will be the next step. Please take a look at my pull request #41 and leave a comment on it there.

**Pull request closed without merging**
