### PR TITLE
Feature/django in root

### PR DESCRIPTION
**Pull request by metalmatze**
So I created a different approach on creating our project structure.

It was inspired by https://github.com/PabloVallejo/todomvc-django which is an django app example.

I've also added the JetBrains and Python `.gitginore`

@juanecabellob has created his version of the project structure, please check it out here: https://github.com/7Pros/circuit/pull/39

### CODE REVIEW

**Comment by Gjum** [comment]
:+1:

**Comment by juanecabellob** [comment]
:+1:

**Comment by metalmatze** [comment]
Ok, I will merge this very soon.

**Comment by Gjum** [comment]
soon™

**Pull request merged**
