### PR TITLE
Set LANGUAGE_CODE and TIME_ZONE to Berlin

### PR DESCRIPTION
**Pull request by metalmatze**

### CODE REVIEW

**Comment by Gjum** [comment]
related [Django Doc](https://docs.djangoproject.com/en/1.8/topics/i18n/timezones/)

**Comment by metalmatze** [comment]
Yeah, it's related, and I read the docs about those settings before. Is there anything wrong?

**Comment by Gjum** [comment]
No, just a reminder for me.

**Comment by Gjum** [comment]
Mh, maybe we want to do everything in english?

**Pull request merged**
