### PR TITLE
Feature/notifications

### LINKED ISSUE #101: As a user, I want to get notifications when other users favorite or repost my posts, mention my name in their posts or add me to a circle
- notify user if they are added for the first time to someone's circle

### PR DESCRIPTION
**Pull request by juanecabellob**
Includes #124.

Closes #101.

### CODE REVIEW

**Comment by Gjum** [comment]
Please merge `upstream/develop` and resolve the merge conflicts.

**Comment by juanecabellob** [comment]
done

**Comment by juanecabellob** [comment]
please do not merge yet, i just did the PR but i will still have a look for code improvements

**Comment by Gjum** [comment]
This conflicts with #124.

**Comment by juanecabellob** [comment]
I know, when the other is merged just let me know and I will handle the merge conflicts

**Comment by metalmatze** [comment]
You should be good to merge this with the current `develop` branch, since I now merged the email notifications.

**Comment by juanecabellob** [comment]
info to this PR and what's coming next. When you have the icon, which I don't think I will be able to make it, all you have to do in order to load it with the desktop notification is to call it notification_icon.png

**Pull request closed without merging**
