### PR TITLE
Improve the design of writing a post

### PR DESCRIPTION
**Pull request by metalmatze**
Before:
download 2

Now:
download 1

### CODE REVIEW

**Comment by Gjum** [comment]
:+1:

**Comment by Gjum** [comment]
@7Pros/devs opinions?

**Comment by nrigheriu** [comment]
looks good to me

**Comment by juanecabellob** [comment]
I would put the button inline with the textarea, so would see more compact and as our style is minimalistic i think it would be better

**Comment by Gjum** [comment]
Will be improved tomorrow by @MetalMatze.

**Pull request merged**
