### PR TITLE
Closes #175

### LINKED ISSUE #175: Login view bug
It is possible to see the login page after being logged in

### PR DESCRIPTION
**Pull request by juanecabellob**

### CODE REVIEW

**Comment by Gjum** [comment]
:+1: for the PR, :-1: for the commit msg

**Comment by metalmatze** [comment]
I would change the order of the `if` and not use `not`.

```
if request.user.is_authenticated():
    return redirect('users:profile', pk=request.user.pk)
else:
    template = loader.get_template('users/user_login.html')
    return HttpResponse(template.render(request=request))
```

That way you will be redirect once authenticated, otherwise the template is shown.

**Comment by Gjum** [comment]
:+1: @MetalMatze

**Comment by juanecabellob** [comment]
it's exactly the same..

**Pull request merged**
